# Welcome to Pumpkin!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.

theme: jekyll-theme-cayman

# Site settings
title:  南瓜&Blog
subtitle: 分享技术，品味人生
name: 南瓜&Blog 
email: pumpkin12666@126.com
description: 本站是pumpkin的技术分享博客。
keywords: pumpkin,C,C++,Python等等
encoding: "utf-8"
favicon: favicon.ico 
